/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl1.ui.contentassist;

import org.xtext.example.mydsl1.ui.contentassist.AbstractLightweightProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LightweightProposalProvider extends AbstractLightweightProposalProvider {
}
