/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl1.scoping;

import org.xtext.example.mydsl1.scoping.AbstractLightweightScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class LightweightScopeProvider extends AbstractLightweightScopeProvider {
}
