/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl1;

import org.xtext.example.mydsl1.LightweightStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LightweightStandaloneSetup extends LightweightStandaloneSetupGenerated {
  public static void doSetup() {
    new LightweightStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
