/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl1;

import org.xtext.example.mydsl1.AbstractLightweightRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LightweightRuntimeModule extends AbstractLightweightRuntimeModule {
}
