/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.mydsl1.ui.AbstractLightweightUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LightweightUiModule extends AbstractLightweightUiModule {
  public LightweightUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
