/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl1.generator;

import com.google.common.base.Objects;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import lightweightDSL.App;
import lightweightDSL.Attribute;
import lightweightDSL.AuthMethod;
import lightweightDSL.Authenticator;
import lightweightDSL.KVALUE;
import lightweightDSL.Knowledge;
import lightweightDSL.LEVEL;
import lightweightDSL.LightweightDSLFactory;
import lightweightDSL.Login;
import lightweightDSL.PROVIDER;
import lightweightDSL.Phase;
import lightweightDSL.Provider;
import lightweightDSL.Recovery;
import lightweightDSL.Registration;
import lightweightDSL.Reset;
import lightweightDSL.Risk;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class LightweightGenerator extends AbstractGenerator {
  /**
   * Authentication method comparator
   */
  public static class MethodComparator implements Comparator<AuthMethod> {
    @Override
    public int compare(final AuthMethod a1, final AuthMethod a2) {
      return a1.getRisk().getValue().compareTo(a2.getRisk().getValue());
    }
  }
  
  /**
   * Authentication Factor
   */
  public static final String POSSESSION = "Possession";
  
  public static final String BIOMETRICS = "Biometrics";
  
  public static final String KNOWLEDGE = "Knowledge";
  
  /**
   * Method af authentication
   */
  public static final String SFA = "SFA";
  
  public static final String MFA = "MFA";
  
  /**
   * Procedures
   */
  public static final String REGISTRATION = "Registration";
  
  public static final String LOGIN = "Login";
  
  public static final String RESET = "Reset";
  
  public static final String RECOVERY = "Recovery";
  
  private Registration mainRegistration;
  
  private Login mainLogin;
  
  private List<Reset> resets = new ArrayList<Reset>();
  
  private List<Recovery> recoveries = new ArrayList<Recovery>();
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    final App app = ((App) _head);
    this.initAuthenticator(app);
    this.initAuthentications(app);
    this.assignMethod(app);
  }
  
  public void initAuthenticator(final App app) {
    EList<Authenticator> _authenticators = app.getAuthenticators();
    for (final Authenticator auth : _authenticators) {
      {
        auth.setRisk(LightweightDSLFactory.eINSTANCE.createRisk());
        String _type = auth.getType();
        if (_type != null) {
          switch (_type) {
            case LightweightGenerator.POSSESSION:
              Risk _risk = auth.getRisk();
              _risk.setInstance(LightweightGenerator.POSSESSION);
              Risk _risk_1 = auth.getRisk();
              _risk_1.setValue(LEVEL.MEDIUM);
              Risk _risk_2 = auth.getRisk();
              _risk_2.setMessage("Use of possession based authenticator");
              Risk _risk_3 = auth.getRisk();
              _risk_3.setInformation("");
              break;
            case LightweightGenerator.BIOMETRICS:
              Risk _risk_4 = auth.getRisk();
              _risk_4.setInstance(LightweightGenerator.BIOMETRICS);
              Risk _risk_5 = auth.getRisk();
              _risk_5.setValue(LEVEL.LOW);
              Risk _risk_6 = auth.getRisk();
              _risk_6.setMessage("Use of biometrics based authenticator");
              Risk _risk_7 = auth.getRisk();
              _risk_7.setInformation("");
              break;
            case LightweightGenerator.KNOWLEDGE:
              final Knowledge knowledgeAuth = ((Knowledge) auth);
              Risk _risk_8 = auth.getRisk();
              _risk_8.setInstance(LightweightGenerator.KNOWLEDGE);
              KVALUE _value = knowledgeAuth.getValue();
              boolean _equals = Objects.equal(_value, KVALUE.PREFERENCES);
              if (_equals) {
                Risk _risk_9 = auth.getRisk();
                _risk_9.setValue(LEVEL.HIGH);
                Risk _risk_10 = auth.getRisk();
                String _name = auth.getName();
                String _plus = ("Use of preference based authenticator " + _name);
                String _plus_1 = (_plus + "!");
                _risk_10.setMessage(_plus_1);
                Risk _risk_11 = auth.getRisk();
                _risk_11.setInformation("");
              } else {
                if ((Objects.equal(knowledgeAuth.getValue(), KVALUE.PIN) || Objects.equal(knowledgeAuth.getValue(), KVALUE.LTBP))) {
                  Risk _risk_12 = auth.getRisk();
                  _risk_12.setValue(LEVEL.MEDIUM);
                  Risk _risk_13 = auth.getRisk();
                  String _name_1 = auth.getName();
                  String _plus_2 = ("Use of low security text based " + _name_1);
                  String _plus_3 = (_plus_2 + "!");
                  _risk_13.setMessage(_plus_3);
                  Risk _risk_14 = auth.getRisk();
                  _risk_14.setInformation("");
                } else {
                  Risk _risk_15 = auth.getRisk();
                  _risk_15.setValue(LEVEL.LOW);
                  Risk _risk_16 = auth.getRisk();
                  String _name_2 = auth.getName();
                  String _plus_4 = ("Use of strong text based authentication " + _name_2);
                  String _plus_5 = (_plus_4 + "!");
                  _risk_16.setMessage(_plus_5);
                  Risk _risk_17 = auth.getRisk();
                  _risk_17.setInformation("");
                }
              }
              if (((!knowledgeAuth.isLimitedAttempts()) || knowledgeAuth.isAutofilled())) {
                boolean _isAutofilled = knowledgeAuth.isAutofilled();
                if (_isAutofilled) {
                  LEVEL _value_1 = auth.getRisk().getValue();
                  boolean _lessThan = (_value_1.compareTo(LEVEL.MEDIUM) < 0);
                  if (_lessThan) {
                    Risk _risk_18 = auth.getRisk();
                    _risk_18.setValue(LEVEL.MEDIUM);
                    auth.getRisk().getMessage().concat("\n The risk is raised because of the use of autofillable form considered as possession-based authentication");
                    Risk _risk_19 = auth.getRisk();
                    _risk_19.setInformation("");
                  }
                } else {
                  LEVEL _value_2 = auth.getRisk().getValue();
                  boolean _equals_1 = Objects.equal(_value_2, LEVEL.MEDIUM);
                  if (_equals_1) {
                    Risk _risk_20 = auth.getRisk();
                    _risk_20.setValue(LEVEL.HIGH);
                    auth.getRisk().getMessage().concat("\n The risk is raised because of the unlimited attempts");
                    Risk _risk_21 = auth.getRisk();
                    _risk_21.setInformation("");
                  }
                  LEVEL _value_3 = auth.getRisk().getValue();
                  boolean _equals_2 = Objects.equal(_value_3, LEVEL.LOW);
                  if (_equals_2) {
                    Risk _risk_22 = auth.getRisk();
                    _risk_22.setValue(LEVEL.MEDIUM);
                    auth.getRisk().getMessage().concat("\n The risk is raised from LOW to MEDIUM because of the unlimited attempts");
                    Risk _risk_23 = auth.getRisk();
                    _risk_23.setInformation("");
                  }
                }
              }
              break;
          }
        }
      }
    }
  }
  
  public void initAuthentications(final App app) {
    EList<AuthMethod> _authMethods = app.getAuthMethods();
    for (final AuthMethod method : _authMethods) {
      String _type = method.getType();
      boolean _equals = Objects.equal(_type, LightweightGenerator.SFA);
      if (_equals) {
        method.setRisk(method.getAuthenticators().get(0).getRisk());
      } else {
        Risk _risk = method.getRisk();
        _risk.setValue(this.maximum(method.getAuthenticators().get(0).getRisk().getValue(), method.getAuthenticators().get(1).getRisk().getValue()));
      }
    }
  }
  
  public void assignMethod(final App app) {
    InputOutput.<String>println("Initializing methods for each phases");
    EList<Phase> _phases = app.getPhases();
    for (final Phase phase : _phases) {
      {
        phase.setRisk(LightweightDSLFactory.eINSTANCE.createRisk());
        String _type = phase.getType();
        if (_type != null) {
          switch (_type) {
            case LightweightGenerator.REGISTRATION:
              final Registration r = ((Registration) phase);
              Risk _risk = r.getRisk();
              _risk.setInstance(LightweightGenerator.REGISTRATION);
              EList<Attribute> _attributes = r.getAttributes();
              for (final Attribute attribute : _attributes) {
                {
                  attribute.setRisk(LightweightDSLFactory.eINSTANCE.createRisk());
                  if ((((!attribute.getVerifmethod().isUniqueness()) && 
                    (!attribute.getVerifmethod().isValidity())) && 
                    (!attribute.getVerifmethod().isBindings()))) {
                    Risk _risk_1 = attribute.getRisk();
                    _risk_1.setValue(LEVEL.HIGH);
                    Risk _risk_2 = attribute.getRisk();
                    String _name = attribute.getName();
                    String _plus = (_name + " : No requirements are satisfied ");
                    _risk_2.setMessage(_plus);
                    Risk _risk_3 = attribute.getRisk();
                    _risk_3.setInformation("");
                  } else {
                    if ((((!attribute.getVerifmethod().isUniqueness()) || 
                      (!attribute.getVerifmethod().isValidity())) || 
                      (!attribute.getVerifmethod().isBindings()))) {
                      Risk _risk_4 = attribute.getRisk();
                      _risk_4.setValue(LEVEL.MEDIUM);
                      Risk _risk_5 = attribute.getRisk();
                      String _name_1 = attribute.getName();
                      String _plus_1 = (_name_1 + ": One or two requirements are unsatisfied");
                      _risk_5.setMessage(_plus_1);
                      Risk _risk_6 = attribute.getRisk();
                      _risk_6.setInformation("");
                    } else {
                      Risk _risk_7 = attribute.getRisk();
                      _risk_7.setValue(LEVEL.LOW);
                      Risk _risk_8 = attribute.getRisk();
                      String _name_2 = attribute.getName();
                      String _plus_2 = (_name_2 + " : All requirements are satisfied");
                      _risk_8.setMessage(_plus_2);
                      Risk _risk_9 = attribute.getRisk();
                      _risk_9.setInformation("");
                    }
                  }
                  PROVIDER _provider = attribute.getProvider();
                  boolean _equals = Objects.equal(_provider, Provider.ID_P);
                  if (_equals) {
                    LEVEL _value = attribute.getRisk().getValue();
                    boolean _lessThan = (_value.compareTo(LEVEL.MEDIUM) < 0);
                    if (_lessThan) {
                      Risk _risk_10 = attribute.getRisk();
                      _risk_10.setValue(LEVEL.MEDIUM);
                      Risk _risk_11 = attribute.getRisk();
                      String _name_3 = attribute.getName();
                      String _plus_3 = (_name_3 + " :Identity provider put the risk to MEDIUM");
                      _risk_11.setMessage(_plus_3);
                      Risk _risk_12 = attribute.getRisk();
                      _risk_12.setInformation("");
                    } else {
                      Risk _risk_13 = attribute.getRisk();
                      _risk_13.setInformation("");
                    }
                  }
                }
              }
              this.mainRegistration = ((Registration) r);
              InputOutput.<String>println("Registration Risk Assessment");
              EList<Attribute> _attributes_1 = this.mainRegistration.getAttributes();
              for (final Attribute attr : _attributes_1) {
                String _name = attr.getName();
                String _plus = ("Attribute (" + _name);
                String _plus_1 = (_plus + ") has risk level (");
                LEVEL _value = attr.getRisk().getValue();
                String _plus_2 = (_plus_1 + _value);
                String _plus_3 = (_plus_2 + ")");
                InputOutput.<String>println(_plus_3);
              }
              break;
            case LightweightGenerator.LOGIN:
              final Login login = ((Login) phase);
              Risk _risk_1 = login.getRisk();
              _risk_1.setInstance(LightweightGenerator.LOGIN);
              int _size = login.getAuthMethods().size();
              boolean _notEquals = (_size != 1);
              if (_notEquals) {
                LightweightGenerator.MethodComparator comp = new LightweightGenerator.MethodComparator();
                ListExtensions.<AuthMethod>sortInplace(login.getAuthMethods(), comp);
                Risk _risk_2 = login.getRisk();
                _risk_2.setValue(IterableExtensions.<AuthMethod>last(login.getAuthMethods()).getRisk().getValue());
                Risk _risk_3 = login.getRisk();
                AuthMethod _last = IterableExtensions.<AuthMethod>last(login.getAuthMethods());
                String _plus_4 = ("Multiple method but, the referenced authentication method is (" + _last);
                String _plus_5 = (_plus_4 + ")");
                _risk_3.setMessage(_plus_5);
                Risk _risk_4 = login.getRisk();
                _risk_4.setInformation("");
                this.mainLogin = ((Login) login);
              } else {
                AuthMethod _get = login.getAuthMethods().get(0);
                String _plus_6 = ("main authentication method" + _get);
                InputOutput.<String>println(_plus_6);
                Risk _risk_5 = login.getRisk();
                AuthMethod _get_1 = login.getAuthMethods().get(0);
                String _plus_7 = ("One referenced authentication method is ( \n " + _get_1);
                String _plus_8 = (_plus_7 + ")");
                _risk_5.setMessage(_plus_8);
                Risk _risk_6 = login.getRisk();
                _risk_6.setValue(login.getAuthMethods().get(0).getRisk().getValue());
                Risk _risk_7 = login.getRisk();
                _risk_7.setInformation("");
                this.mainLogin = ((Login) login);
              }
              boolean _isSession = login.isSession();
              if (_isSession) {
                this.mainLogin.getRisk().getMessage().concat("\n ----- Persisted Session detected ------\n The risk level is at most Medium ");
                Risk _risk_8 = this.mainLogin.getRisk();
                _risk_8.setValue(this.maximum(this.mainLogin.getRisk().getValue(), LEVEL.MEDIUM));
                this.mainLogin.getRisk().getInformation().concat("");
              }
              InputOutput.<String>println("Login Risk Assessment");
              String _name_1 = this.mainLogin.getName();
              String _plus_9 = ("Login risk level : \n name : " + _name_1);
              String _plus_10 = (_plus_9 + "\n\t\t\t\t\t\t\t\n Evaluation : ");
              String _string = this.mainLogin.getRisk().toString();
              String _plus_11 = (_plus_10 + _string);
              InputOutput.<String>println(_plus_11);
              break;
            case LightweightGenerator.RESET:
              final Reset reset = ((Reset) phase);
              Risk _risk_9 = reset.getRisk();
              _risk_9.setInstance(LightweightGenerator.RESET);
              int _size_1 = reset.getAuthMethods().size();
              boolean _equals = (_size_1 == 0);
              if (_equals) {
                Risk _risk_10 = reset.getRisk();
                _risk_10.setInformation("It is highly recommended to use a security challenge to before reseting credential and also before sensitive action such as payment");
                boolean _isSession_1 = this.mainLogin.isSession();
                if (_isSession_1) {
                  Risk _risk_11 = reset.getRisk();
                  _risk_11.setValue(this.maximum(LEVEL.MEDIUM, this.mainLogin.getRisk().getValue()));
                  Risk _risk_12 = reset.getRisk();
                  _risk_12.setMessage("Because of the persistent session the risk level is at most MEDIUM (considered as Possession based");
                } else {
                  Risk _risk_13 = reset.getRisk();
                  _risk_13.setValue(this.mainLogin.getRisk().getValue());
                  Risk _risk_14 = reset.getRisk();
                  String _name_2 = reset.getName();
                  String _plus_12 = ("No Persistent Session : The risk level of the Reset (" + _name_2);
                  String _plus_13 = (_plus_12 + ") is given by the MainLogin (");
                  String _name_3 = this.mainLogin.getName();
                  String _plus_14 = (_plus_13 + _name_3);
                  String _plus_15 = (_plus_14 + ")");
                  _risk_14.setMessage(_plus_15);
                }
              } else {
                LightweightGenerator.MethodComparator comp_1 = new LightweightGenerator.MethodComparator();
                ListExtensions.<AuthMethod>sortInplace(reset.getAuthMethods(), comp_1);
                Risk _risk_15 = reset.getRisk();
                String _string_1 = IterableExtensions.<AuthMethod>last(reset.getAuthMethods()).toString();
                String _plus_16 = ("Multiple method but, the referenced authentication method is (\n" + _string_1);
                String _plus_17 = (_plus_16 + ")");
                _risk_15.setMessage(_plus_17);
                reset.getRisk().getMessage().concat("\n, Reset Challenge with no persistent challenge : The risk level is at LEAST the ");
                Risk _risk_16 = reset.getRisk();
                _risk_16.setValue(this.maximum(IterableExtensions.<AuthMethod>last(reset.getAuthMethods()).getRisk().getValue(), this.mainLogin.getRisk().getValue()));
                String _message = reset.getRisk().getMessage();
                String _string_2 = IterableExtensions.<AuthMethod>last(reset.getAuthMethods()).toString();
                String _plus_18 = ("\n, Reset Challenge with no persistent challenge : The risk level is evaluated as two factor authentication between the Challenge (" + _string_2);
                String _plus_19 = (_plus_18 + ") and the mainLogin authentication (");
                String _string_3 = IterableExtensions.<AuthMethod>last(this.mainLogin.getAuthMethods()).toString();
                String _plus_20 = (_plus_19 + _string_3);
                String _plus_21 = (_plus_20 + ")");
                _message.concat(_plus_21);
              }
              InputOutput.<String>println("Reset Risk Assessment");
              String _name_4 = reset.getName();
              String _plus_22 = ("Reset risk level : \n name : " + _name_4);
              String _plus_23 = (_plus_22 + "\n\t\t\t\t\t\t\t\n Evaluation : ");
              String _string_4 = reset.getRisk().toString();
              String _plus_24 = (_plus_23 + _string_4);
              InputOutput.<String>println(_plus_24);
              this.resets.add(reset);
              break;
            case LightweightGenerator.RECOVERY:
              break;
          }
        }
      }
    }
  }
  
  /**
   * Max between level
   */
  public LEVEL maximum(final LEVEL l1, final LEVEL l2) {
    int _value = l1.getValue();
    int _value_1 = l2.getValue();
    boolean _lessEqualsThan = (_value <= _value_1);
    if (_lessEqualsThan) {
      return l1;
    }
    return l2;
  }
  
  /**
   * Max between risk
   */
  public Risk maximum(final Risk r1, final Risk r2) {
    LEVEL _value = r1.getValue();
    LEVEL _value_1 = r2.getValue();
    boolean _lessEqualsThan = (_value.compareTo(_value_1) <= 0);
    if (_lessEqualsThan) {
      return r1;
    }
    return r2;
  }
}
