/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl1.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl1.LightweightRuntimeModule;
import org.xtext.example.mydsl1.LightweightStandaloneSetup;
import org.xtext.example.mydsl1.ide.LightweightIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LightweightIdeSetup extends LightweightStandaloneSetup {
  @Override
  public Injector createInjector() {
    LightweightRuntimeModule _lightweightRuntimeModule = new LightweightRuntimeModule();
    LightweightIdeModule _lightweightIdeModule = new LightweightIdeModule();
    return Guice.createInjector(Modules2.mixin(_lightweightRuntimeModule, _lightweightIdeModule));
  }
}
