/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl1.ide;

import org.xtext.example.mydsl1.ide.AbstractLightweightIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LightweightIdeModule extends AbstractLightweightIdeModule {
}
